### ISSUE TITLE
Error when processing groups that have users from the local domain and remote domain 

### ISSUE THREAD

**Issue by pb1212** [lazywinadmin/PowerShell#16]
Hi

I get an error while processing groups that have users from other domains within a group.  I have checked by removing members that are from the other domain and running again. Once the user has been removed there is no error. 

Is it possible to query groups that have users from multiple domains? If not is it something that can be addressed? 

ERROR being generated. 

"WARNING: The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.
WARNING: [PROCESS] AD MODULE - Error When querying the group <GROUP-NAME>members in Active Directory
WARNING: The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.

**Comment by lazywinadmin** [comment]
Thanks for reporting this @pb1212 

Yeah the script does not support cross domain and can't think about workaround.
I'll add this in the todo but can't commit for any changes soon
