### ISSUE TITLE
Its not an issue but need help in sending outlook mail using powershell script

### ISSUE THREAD

**Issue by vishnuprakash9845** [lazywinadmin/PowerShell#33]
I am an automation engineer

I have have automated few test cases and getting the test results. This test results I wanted to forward to team using outlook using powershell. I tried many ways to do it, but not working. Can anyone please help me out in this.

**Comment by lazywinadmin** [comment]
Typically to send email via PowerShell, your code talk directly to the SMTP server.
PowerShell acts as a SMTP client in this case, Outlook does the same thing with an User interface.

You can leverage the built-in cmdlet [Send-MailMessage](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-7.1)
