### ISSUE TITLE
TOOL-Enable-RemoteDesktop

### ISSUE THREAD

**Issue by TechASP** [lazywinadmin/PowerShell#4]
Win32_TerminalServiceSetting doesn't work with standart parameter, I need to use 

> Authentication 

with value

> PacketPrivacy

	$Splatting = @{
		Class = "Win32_TerminalServiceSetting"
		NameSpace = "root\cimv2\terminalservices"
		ComputerName = $Computer
		Authentication = 'PacketPrivacy'
		ErrorAction = 'Stop'
		ErrorVariable = 'ErrorProcessGetWmi'
	}

**Comment by lazywinadmin** [comment]
Thanks for your comment  @TechASP 
Indeed I see that in the following document (in the remarks) [Win32_TerminalServiceSetting class](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383640(v=vs.85).aspx) requires to include it.

I just updated the function
