### ISSUE TITLE
TOOL-Remove-StringSpecialCharacter - Minus sign in regex

### ISSUE THREAD

**Issue by hegedusg** [lazywinadmin/PowerShell#6]
If  SpecialCharacterToKeep contains minus sign the result is wrong. For example: 
Remove-StringSpecialCharacter -String "wow#@!`~)(\|?/}{-_=+*" -SpecialCharacterToKeep "*","_","-","/" returns  wow/_* 
The solution is to escape minus sign. Something like this:  IF ($Character -eq "-") {$Regex +="\-"} else {$Regex += [Regex]::Escape($Character)} 

Other problem is that the forward slash in front of the special characters seems unnecessary in line $Regex += "/$character"

**Comment by lazywinadmin** [comment]
Thanks @hegedusg ! Great input! Should have thought of it!
Will update the code this week-end! Really appreciated!

**Comment by lazywinadmin** [comment]
Whoups forgot about this one. Correct in this commit: https://github.com/lazywinadmin/PowerShell/commit/c45d1a7733c66c27fdd4d3c309da6cc3d031fd80

Thanks again @hegedusg
